# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dexie.js - Minimalistic IndexedDB Wrapper
email: david.fahlander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dexie.js documentation.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "http://dexie.org" # the base hostname & protocol for your site
twitter_username: dfahlander
github_username:  dfahlander
include: ['docs']
kramdown:
  input: GFM

# Build settings
markdown: kramdown
